[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gm = "F5QnEMWv3mqzd9sbEy2Zpoipw3ajNiH6bGdWFimoBQxy"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "~/.config/solana/id.json"
cluster = "http://127.0.0.1:8898"
url = "http://127.0.0.1:8900"


[faucet]
port = 9901


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
